name: Greeting on variable day

on:
  workflow_dispatch

# Global Variables
env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    # Job Variables
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        # Step Variables
        env:
          First_Name: Mona
